setw -g mode-keys vi
set -g mouse on

# Terminal type configuration
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"

# Local tmux uses C-a
unbind C-b
set -g prefix C-a
bind-key -n C-a send-prefix

# Scrollback
set -g history-limit 50000

# Tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sessionist'

# Initialize Tmxu plugin manager
run -b '~/.tmux/plugins/tpm/tpm'
