setw -g mode-keys vi
set -g mouse on
set -s escape-time 0

# Terminal type configuration
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"

# Local tmux uses C-a
unbind C-b
set -g prefix C-a
bind-key -n C-a send-prefix

