theme = "arboreal"

[editor]
auto-format = true
bufferline = "multiple"
default-yank-register = "+"
line-number = "relative"
true-color = true
jump-label-alphabet = "asdfghjklqweruiop"
end-of-line-diagnostics = "warning"
clipboard-provider = "pasteboard"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-inlay-hints = false
display-messages = true

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25         # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""   # set wrap-indicator to "" to hide it

[keys.normal]
H = ":bp"
L = ":bn"
- = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"

# LSP/Treesitter selection stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"


[keys.normal.space.u]
h = ":toggle lsp.display-inlay-hints"

[keys.normal.space]
l = ":format"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
"C-l" = ":format"

[keys.normal.g]
ret = [":write-all", ":insert-output serpl >/dev/tty", ":redraw", ":reload-all"]

[keys.normal."["]
"[" = "flip_selections"

[keys.select]
"D" = "remove_primary_selection"
"-" = "merge_selections"
"[" = "flip_selections"
"_" = "split_selection_on_newline"
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
