start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 120

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true


[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
alt-ctrl-cmd-shift-comma = 'mode xservice'
alt-ctrl-cmd-shift-w = 'mode window'
alt-ctrl-cmd-shift-space = 'mode layout'
alt-ctrl-cmd-shift-r = 'mode resize'
alt-ctrl-cmd-shift-s = 'mode split'
alt-ctrl-cmd-shift-p = 'mode picker'

alt-ctrl-cmd-shift-h = 'focus left'
alt-ctrl-cmd-shift-j = 'focus down'
alt-ctrl-cmd-shift-k = 'focus up'
alt-ctrl-cmd-shift-l = 'focus right'
alt-ctrl-cmd-shift-f = 'fullscreen'

[mode.layout.binding]
esc = "mode main"

alt-ctrl-cmd-shift-f = 'layout floating tiling'
alt-ctrl-cmd-shift-t = 'layout tiles horizontal vertical'
alt-ctrl-cmd-shift-a = 'layout accordion horizontal vertical'

[mode.window.binding]
esc = "mode main"

alt-ctrl-cmd-shift-h = 'move left'
alt-ctrl-cmd-shift-j = 'move down'
alt-ctrl-cmd-shift-k = 'move up'
alt-ctrl-cmd-shift-l = 'move right'

alt-ctrl-cmd-shift-1 = [
  'move-node-to-workspace 1 --focus-follows-window',
  'mode main',
]
alt-ctrl-cmd-shift-2 = [
  'move-node-to-workspace 2 --focus-follows-window',
  'mode main',
]
alt-ctrl-cmd-shift-3 = [
  'move-node-to-workspace 3 --focus-follows-window',
  'mode main',
]
alt-ctrl-cmd-shift-4 = [
  'move-node-to-workspace 4 --focus-follows-window',
  'mode main',
]
alt-ctrl-cmd-shift-5 = [
  'move-node-to-workspace 5 --focus-follows-window',
  'mode main',
]
alt-ctrl-cmd-shift-t = [
  'move-node-to-workspace notes --focus-follows-window',
  'mode main',
]
alt-ctrl-cmd-shift-c = [
  'move-node-to-workspace comms --focus-follows-window',
  'mode main',
]
alt-ctrl-cmd-shift-a = [
  'move-node-to-workspace admin --focus-follows-window',
  'mode main',
]
alt-ctrl-cmd-shift-m = [
  'move-node-to-workspace music --focus-follows-window',
  'mode main',
]
alt-ctrl-cmd-shift-o = [
  'move-node-to-workspace obs --focus-follows-window',
  'mode main',
]

alt-ctrl-cmd-shift-n = [
  'move-workspace-to-monitor --wrap-around next',
  'mode main',
]
alt-ctrl-cmd-shift-p = [
  'move-workspace-to-monitor --wrap-around prev',
  'mode main',
]

alt-ctrl-cmd-shift-equal = ['balance-sizes', 'mode main']

[mode.split.binding]
esc = "mode main"

alt-ctrl-cmd-shift-h = 'join-with left'
alt-ctrl-cmd-shift-j = 'join-with down'
alt-ctrl-cmd-shift-k = 'join-with up'
alt-ctrl-cmd-shift-l = 'join-with right'

[mode.picker.binding]
esc = "mode main"

tab = 'workspace-back-and-forth'
alt-ctrl-cmd-shift-1 = ['workspace 1', 'mode main']
alt-ctrl-cmd-shift-2 = ['workspace 2', 'mode main']
alt-ctrl-cmd-shift-3 = ['workspace 3', 'mode main']
alt-ctrl-cmd-shift-4 = ['workspace 4', 'mode main']
alt-ctrl-cmd-shift-5 = ['workspace 5', 'mode main']
alt-ctrl-cmd-shift-t = ['workspace notes', 'mode main']
alt-ctrl-cmd-shift-c = ['workspace comms', 'mode main']
alt-ctrl-cmd-shift-a = ['workspace admin', 'mode main']
alt-ctrl-cmd-shift-m = ['workspace music', 'mode main']
alt-ctrl-cmd-shift-o = ['workspace obs', 'mode main']

alt-ctrl-cmd-shift-n = ['focus-monitor --wrap-around next', 'mode main']
alt-ctrl-cmd-shift-p = ['focus-monitor --wrap-around prev', 'mode main']

[mode.summon.binding]
esc = "mode main"

alt-ctrl-cmd-shift-1 = ['summon-workspace 1', 'mode main']
alt-ctrl-cmd-shift-2 = ['summon-workspace 2', 'mode main']
alt-ctrl-cmd-shift-3 = ['summon-workspace 3', 'mode main']
alt-ctrl-cmd-shift-4 = ['summon-workspace 4', 'mode main']
alt-ctrl-cmd-shift-5 = ['summon-workspace 5', 'mode main']
alt-ctrl-cmd-shift-t = ['summon-workspace notes', 'mode main']
alt-ctrl-cmd-shift-c = ['summon-workspace comms', 'mode main']
alt-ctrl-cmd-shift-a = ['summon-workspace admin', 'mode main']
alt-ctrl-cmd-shift-m = ['summon-workspace music', 'mode main']
alt-ctrl-cmd-shift-o = ['summon-workspace music', 'mode main']

[mode.resize.binding]
esc = "mode main"

alt-ctrl-cmd-shift-minus = 'resize smart -50'
alt-ctrl-cmd-shift-equal = 'resize smart +50'

[mode.xservice.binding]
esc = "mode main"

alt-ctrl-cmd-shift-comma = ['reload-config', 'mode main']
alt-ctrl-cmd-shift-r = ['flatten-workspace-tree', 'mode main']                # reset layout
alt-ctrl-cmd-shift-f = ['layout floating tiling', 'mode main']
alt-ctrl-cmd-shift-backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = "com.github.wez.wezterm"
run = "layout tiling"

[[on-window-detected]]
if.app-id = "uk.co.wearecocoon.YT-Music"
run = "move-node-to-workspace music"

[[on-window-detected]]
if.app-id = "com.linear"
run = "move-node-to-workspace admin"

[[on-window-detected]]
if.app-id = "com.tinyspeck.slackmacgap"
run = "move-node-to-workspace comms"

[[on-window-detected]]
if.app-id = "com.1password.1password"
run = "move-node-to-workspace admin"

[[on-window-detected]]
if.app-id = "md.obsidian"
run = "move-node-to-workspace notes"

[[on-window-detected]]
if.app-id = "com.obsproject.obs-studio"
run = "move-node-to-workspace obs"

[[on-window-detected]]
if.app-id = "us.zoom.xos"
run = "move-node-to-workspace comms"
